---
title: "Marine-Genomics-BBD"
author: "CaterinaPalma"
date: "2026-07-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  include = TRUE,
  message = FALSE,
  warning = FALSE)
```

# Assembly 

First I need to go into the directory I have already made called "Workshop_4_Metagenome_Function" I do this by: 

```bash
cd Marine_Genomics_Workshop_4
``` 

Now I can begin with step 1. 


#### Step 1: Making a directory called flye 

```bash 
mkdir flye
cd flye
```

#### Step 2: Make a symbolic link to the bbd read area 

```bash 
ln -s /pvol/data/metagenome_assembly/bbd_0.1.fastq.gz .
```

#### Step 3: Make shell script and put below into it 

#!/bin/bash
#SBATCH --time=720
#SBATCH --ntasks=12 --mem=10gb

echo "Starting flye bbd in $(pwd) at $(date)"

flye --nano-hq ../flye/bbd_0.1.fastq.gz --threads 12 --out-dir bbd --meta

echo "Finished flye bbd in $(pwd) at $(date)"

#### Step 4: Submit the job 

```bash 
sbatch run_flye_bbd.sh
``` 
Output: job 490 (slurm-438)

I can monitor job progress using: 

```bash 
tail -f slurm-507.out
``` 

# Binning & Checking Bin Quality 

#### Step 1. Make New Directory "metabat" and go to the directory 

```bash
mkdir metabat
cd metabat
``` 

#### Step 2. Extract Depth Information 

```bash 
cat ../flye/bbd/assembly_info.txt  | grep -v '#' | awk '{OFS="\t";print $1,$3}' > depths_bbd.txt
```

#### Step 3. Reorder contigs based on depth

```bash
cat depths_bbd.txt | awk '{print $1}' | xargs samtools faidx ../flye/bbd/assembly.fasta > assembly_bbd_ordered.fasta
```

#### Step 4. Run Metabat 

```bash
metabat2 -i assembly_bbd_ordered.fasta -a depths_bbd.txt --cvExt -o bins_bbd/metabat --seed 5
``` 

#### Step 5. Check bin quality with checkm 

Make sure I'm not in any other directory 

```bash
pwd
cd .. 
``` 

Make a new directory 

```bash 
mkdir checkm
cd checkm
``` 

#### Step 6. You will need to find the number of your largest contig in the bbd assembly 

```bash 
cat ../flye/bbd/assembly.fasta | bioawk -c fastx '{print length($seq),$name}' | sort -n
``` 

Once you have found the longest contig substitute its name instead of contig_XX in the code below.

```bash 
mkdir bins_bbd
cp ../metabat/bins_bbd/*.fa bins_bbd/
samtools faidx ../flye/bbd/assembly.fasta contig_120 > bins_bbd/contig_120.fa
``` 

#### Step 7. Create a slurm script for checkm run. 
Script called "run_checkm_bbd.sh". Put the below in the shell script: 

#!/bin/bash
#SBATCH --time=60
#SBATCH --ntasks=6 --mem=60gb

echo "Starting checkm in $(pwd) at $(date)"

shopt -s expand_aliases
alias checkm='apptainer run -B /pvol/:/pvol /pvol/data/sif/checkm.sif checkm'

checkm lineage_wf bins_bbd out -t 4 -x fa -f checkm_results_bbd.txt

echo "Finished checkm in $(pwd) at $(date)"

#### Step 8. Submit sm job: 

```bash
sbatch run_checkm_bbd.sh
``` 

Output: batch slurm-559

Check where I am in queue: 

```bash
squeue
``` 

# Select bins based on checkm results

#### Step 1. Make sure I'm in "checkm" directory 

```bash
cd checkm
```

#### Step 2. Results are summarised in file "checkm_results_bbd.txt" 

You can view the results in the terminal using cat, head, more or less commands. These all represent different ways to view a text file.

```bash
head checkm_results_bbd.txt 
```

#### Step 3. Take a look at the Marker lineage column for the top few bins.
Try viewing a few more results by telling the head command to show more lines

```bash
head -n 20 checkm_results_bbd.txt 
``` 

#### Step 4. Focusing on bins with a completeness greater than 15% using "awk". 

```bash 
cat checkm_results_bbd.txt | awk '$13>15'
``` 

#### Step 5. These are the bins we want but we just want the bin ID not the entire line. 
To get this we can use the print command: 

```bash 
cat checkm_results_bbd.txt | awk '$13>15{print $1}'
``` 

#### Step 6. Sening output to a file so that we can use it in the next step: 

```bash 
cat checkm_results_bbd.txt | awk '$13>15{print $1}' > bbd_topbins.txt
``` 

# Perform taxonomic classification with gtdbtk

Go to main directory

```bash
cd ..
``` 

#### Step 1. Make new directory called "gtdbtk" 

```bash 
mkdir gtdbtk
cd gtdbtk
```

#### Step 2. Create sub-folder 
This is where we will put a copy of each of the top bins we identified in step 1.

```bash 
mkdir genomes
``` 

#### Step 3. Building a command in steps: 
We’ll build up the command in steps. First just get the while loop working

```bash 
while read bin;do echo $bin;done < ../gtdbtk/genome/bbd_topbins.txt
``` 

```bash
while read bin;do echo "../metabat/bins_bbd/${bin}.fa";done < ../checkm/bbd_topbins.txt
``` 

```bash
while read bin;do cp "../metabat/bins_bbd/${bin}.fa" genomes;done < ../checkm/bbd_topbins.txt
``` 

#### Step 4. Check that it worked by listing files within the genomes directory. You should see one file for each of the bins: 

```bash 
ls genome
``` 

#### Step 5. Make shell script 
Make a shell script with the below named: "run_gtdbtk.sh" 

#!/bin/bash
#SBATCH --time=60
#SBATCH --ntasks=2 --mem=40gb

echo "Starting gtdbtk in $(pwd) at $(date)"

shopt -s expand_aliases
alias gtdbtk='apptainer run -B /pvol:/pvol,/pvol/data/mg/gtdbtkdata/release207_v2/:/refdata /pvol/data/sif/gtdbtk.sif'

gtdbtk classify_wf -x fa --cpus 2 --genome_dir genomes --out_dir out --skip_ani_screen

echo "Finished gtdbtk in $(pwd) at $(date)"

#### Step 6. Submit 

```bash 
sbatch run_gtdbtk.sh
``` 

Output: slurm-580

```bash
squeue
```

# Find and Anotate Genes with prokka 

#### Step 1. Make new directory 

```bash
mkdir prokka
cd prokka
``` 

#### Step 2. Running prokka for single bin 
This produces quite a bit of output. Watch the output as it goes by. This output gives a good idea of the various steps prokka goes through.

Find out the first bin ID in your list
```bash 
head -n 1 ../checkm/bbd_topbins.txt
``` 

Output: contig_120 


```bash 
bin=contig_120
prokka --outdir $bin --prefix $bin  ../metabat/bins_bbd/${bin}.fa
``` 

#### Step 4. Create a new blank text file 
Save it in your prokka directory. Call it run_prokka.sh and copy the following code into it.

#!/bin/bash
#SBATCH --time=60
#SBATCH --ntasks=2 --mem=40gb

echo "Starting prokka in $(pwd) at $(date)"

shopt -s expand_aliases
alias prokka='apptainer run -B /pvol/:/pvol /pvol/data/sif/prokka.sif prokka'

while read bin;do 
  prokka --outdir $bin --prefix $bin "../metabat/bins_bbd/${bin}.fa";
done < ../checkm/bbd_topbins.txt

echo "Finished prokka in $(pwd) at $(date)"

submit job: 

```bash
sbatch run_prokka.sh
```

Output: slurm-599 

# Infer Metabolic Pathways 

#### Step 1. Create new directory 

First make sure we''re in main directory... 

```bash
cd .. 
mkdir minpath
cd minpath
``` 

#### Step 2. Start by looking at the .tsv file for a single bin: 

```bash
head ../prokka/contig_120/contig_120.tsv
``` 

#### Step 3. For input to minpath 
We only want to keep a unique ID for each gene (column 1) and its EC number (column 5). We can transform the tsv into this format using awk like this. 

```bash
head ../prokka/contig_120/contig_120.tsv | awk -F '\t' '{print $1,$5}'
``` 

#### Step 4. Filter the output to only include lines with an EC number

```bash
head ../prokka/contig_120/contig_120.tsv | awk -F '\t' '$5{print $1,$5}'
``` 

#### Step 5. Ensure that the output is tab separated 
and we also need to remove the header line. 

```bash
head ../prokka/contig_120/contig_120.tsv | awk -F '\t' '$5{OFS="\t";print $1,$5}' | grep -v '^locus'
```

#### Step 6. This only processes the first 10 lines 
… we need to change head to cat to include all genes 

```bash 
cat ../prokka/contig_120/contig_120.tsv | awk -F '\t' '$5{OFS="\t";print $1,$5}' | grep -v '^locus'
``` 

#### Step 7. Send the output to a file 
so that it can be used as input to minpath

```bash 
cat ../prokka/contig_120/contig_120.tsv | awk -F '\t' '$5{OFS="\t";print $1,$5}' | grep -v '^locus' > contig_120.ec
``` 

#### Step 8. Run minpath on this file as follows: 

```bash
minpath -ec contig_120.ec -report contig_120.ec.report -details contig_120.ec.details
``` 

### Step 9. Take a look at the top few lines of output

```bash
head contig_120.ec.report 
```

My First Line: 
path PWY-7321 any n/a  naive 1  minpath 0  fam0  4  fam-found  1  name  ecdysteroid metabolism (arthropods)

#### Step 10. 

```bash
while read bin;do 
  cat ../prokka/$bin/${bin}.tsv | awk -F '\t' '$5{printf("%s\t%s\n", $1,$5)}' | grep -v '^locus' > ${bin}.ec 
done < ../checkm/bbd_topbins.txt
``` 

#### Step 11. 

```bash
while read bin;do 
  minpath -ec ${bin}.ec -report ${bin}.ec.report -details ${bin}.ec.details
done < ../checkm/bbd_topbins.txt
```

#### Step 12. Photosynthesis light reactions: 

There is a huge amount of information in the outputs from minpath. To keep things tractable we are just going to look at two pathways.

The first pathway is named photosynthesis light reactions and has the metacyc code PWY-101. This pathway includes the essential components of photosynthesis that occur in light, Photosystem I and Photosystem II.

Use the following command to search for this pathway across all the bins

```bash
grep 'PWY-101' *.ec.report
```

###### Question 
How many bins contain at least one gene from this pathway? 4 bins 
Which bin has all of the genes (ie. a complete pathway)? metabat.32 


#### Step 12. Cross Reference Results 
Cross reference your results with the output from gtdbtk to see the taxonomy of bins containing this pathway. Note that you will need to modify the commands below to use the correct bin numbers (these will be different for everyone).

```bash
grep 'metabat.32' ../gtdbtk/out/gtdbtk.bac120.summary.tsv
``` 

The second pathway is a little less obviously named. It is called superpathway of tetrathionate reduction and has metacyc code PWY-5360. This pathway is important because it includes enzymes required to reduce sulfite to hydrogen sulfide. Note that sulfite acts as the terminal electron acceptor in this pathway, however, in a broader sense the term “sulfate reducing” refers to micro-organisms that can produce sulfide from a range of oxidised sulfur compounds.

###### Question 

```bash
grep 'PWY-5360' *.ec.report
```

How many bins contain the pathway PWY-5360? one - metabat.33 
What family (in a taxonomic sense) do these bins belong to? f__Arcobacteraceae (family) and g__Halarcobacter (genus) 
